### PR TITLE
Update release instructions to include cheatsheet

### PR DESCRIPTION
**Pull request by Innixma**
*Issue #, if available:*

*Description of changes:*
- Update release instructions to include cheatsheet

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by yinweisu — COMMENTED** [review]
We should add uploading the pdf to the correct s3 bucket as a step as well. But maybe we shouldn't specify the s3 bucket in the README for security reason

**Comment by Innixma** [comment]
> We should add uploading the pdf to the correct s3 bucket as a step as well. But maybe we shouldn't specify the s3 bucket in the README for security reason

I'm actually proposing a different strategy, link to the files hosted on GitHub (refer to links I added in this PR). This way we won't have to deal with re-uploading to S3.

**Comment by yinweisu** [comment]
> > We should add uploading the pdf to the correct s3 bucket as a step as well. But maybe we shouldn't specify the s3 bucket in the README for security reason
> 
> I'm actually proposing a different strategy, link to the files hosted on GitHub (refer to links I added in this PR). This way we won't have to deal with re-uploading to S3.

I see. This makes sense.

**Review by yinweisu — APPROVED** [review]

**Comment by szha** [comment]
Job PR-1746-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1746/2/index.html

**Pull request merged**
