### PR TITLE
[WIP] Accelerating Tabular NN

### PR DESCRIPTION
**Pull request by zhanghang1989**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by zhanghang1989** [comment]
This PR speedup the NN model.

For train_data = task.Dataset(file_path='https://autogluon.s3-us-west-2.amazonaws.com/datasets/Inc/train.csv'), the training time is reduced from 256s to 162s.

**Comment by Innixma** [comment]
Was this done with or without Intel MKL?

**Comment by zhanghang1989** [comment]
This is without MKL. I found MKL even slowing down the speed and print a lot of warnings.

**Comment by szha** [comment]
Job PR-291-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-291/1/index.html

**Comment by Innixma** [comment]
Does this speed up inference?

**Comment by zhanghang1989** [comment]
It should also speedup inference time.

**Comment by Innixma** [comment]
Excited to try it out!

**Pull request merged**
