### PR TITLE
[CI] Fix torchvision dataset url

### PR DESCRIPTION
**Pull request by zhreshold**
*Issue #, if available:*

*Description of changes:*
Inject the s3 url to replace mnist download link

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Innixma** [comment]
@zhreshold seems there is still a bug somewhere in this PR.

**Comment by szha** [comment]
Job PR-998-5 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-998/5/index.html

**Comment by zhreshold** [comment]
@Innixma passed

**Review by Innixma — APPROVED** [review]
Looks good!

**Pull request merged**
