### PR TITLE
[Refactoring] Distributed code refactoring

### PR DESCRIPTION
**Pull request by gradientsky**
*Description of changes:*
WIP

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-835-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-835/2/index.html

**Comment by szha** [comment]
Job PR-835-4 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-835/4/index.html

**Comment by szha** [comment]
Job PR-835-5 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-835/5/index.html

**Comment by szha** [comment]
Job PR-835-8 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-835/8/index.html

**Review by Innixma — APPROVED** [review]
Looks good!

**Pull request merged**
