### PR TITLE
[CI] separate unittest in parallel nodes

### PR DESCRIPTION
**Pull request by zhreshold**
*Issue #, if available:*

*Description of changes:*
Separate modular unittests into parallel jenkins nodes, to speed up the tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Innixma** [comment]
@zhreshold any idea why CI failed for only two of the unittest runs? It looks like some kind of transient error.

**Comment by szha** [comment]
Job PR-773-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-773/3/index.html

**Comment by zhreshold** [comment]
@Innixma it's green now

**Review by Innixma — APPROVED** [review]

**Comment by Innixma** [comment]
> @Innixma it's green now

Happy to merge this, but do you have any idea what occurred in the failed run? We'd ideally like to eliminate any CI instability.

**Pull request merged**
