### PR TITLE
Add CodeQL security scanning

### PR DESCRIPTION
**Pull request by jhutchings1**
Hi, I'm a PM on the GitHub security team. This repository is eligible to try the new [GitHub Advanced Security code scanning](https://help.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/about-code-scanning) beta.

Code scanning runs a static analysis tool called CodeQL which scans your code at build time to find any potential security issues. We've tuned the set of queries to be only the most severe, most precise issues. We'll show alerts in the security tab, and we'll show alerts for any net new vulnerabilities on pull requests as well. We've tried to make this super developer friendly, but we'd love your feedback as we work through the beta. 

If you're interested in trying it out, you can merge this pull request to set up the Actions workflow. You can also get this set up yourself in any additional repositories in this organization by following these [instructions](https://help.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning)

### CODE REVIEW

**Comment by szha** [comment]
Job PR-503-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-503/1/index.html

**Comment by jhutchings1** [comment]
@zhreshold That's configurable, but we default to running security queries from https://github.com/github/codeql. The specific queries we're running by default (which depend on the languages scanned) include issues like: 

<summary>Rules</summary>
<details>

Uncontrolled data used in path expression
Uncontrolled command line
XPath injection
URL redirection from remote source
Arbitrary file write during zip extraction   (Zip Slip)
Incomplete regular expression for hostnames
Clear-text logging of sensitive information
Use of externally-controlled format string
Use of a broken or weak cryptographic   algorithm
Reflected cross-site scripting
Regular expression injection
SQL query built from user-controlled sources
Insecure randomness
Clear text storage of sensitive information
Hard-coded credentials
Incomplete URL scheme check
Information exposure through a stack trace
Incomplete URL substring sanitization
Code injection
Information exposure through an exception
Cross-site scripting
LDAP query built from user-controlled   sources
Database query built from user-controlled   sources
Deserialization of user-controlled data
Uncontrolled data in SQL query
Use of a predictable seed in a secure random   number generator
Unsafe jQuery plugin
Overflow in uncontrolled allocation size
Useless regular-expression character escape
Pointer overflow check
Uncontrolled format string
Polynomial regular expression used on   uncontrolled data
Unvalidated local pointer arithmetic
Potentially overflowing call to snprintf
Use of insecure SSL/TLS version
Potentially unsafe external link
Using a package with a known vulnerability
Potentially unsafe quoting
Uncontrolled data used in network request
Prototype pollution
Unsafe dynamic method access
Prototype pollution in utility function
Untrusted XML is read insecurely
Query built from user-controlled sources
Missing X-Frame-Options HTTP header
Query built without neutralizing special   characters
Use of dangerous function
Reading from a world writable file
Use of potentially dangerous function
Missing rate limiting
User-controlled data in numeric cast
Reflected server-side cross-site scripting
Missing cross-site request forgery token   validation
Missing regular expression anchor
Uncontrolled data used in a WebClient
Replacement of a substring with itself
Missing CSRF middleware
Resolving XML external entity in   user-controlled data
Unnecessary use of `cat` process
Resource injection
Unsafe expansion of self-closing HTML tag
Result of multiplication cast to wider type
Unsafe shell command constructed from   library input
ScriptEngine evaluation
Unvalidated dynamic method call
Server Side Template Injection
Upcast array used in pointer arithmetic
Server-side URL redirect
Multiplication result converted to larger   type
Setting a DACL to NULL in a   SECURITY_DESCRIPTOR
Use of a version of OpenSSL with Heartbleed
Shell command built from environment values
No space for zero terminator
Signed overflow check
Use of password hash with insufficient   computational effort
Size computation for allocation may overflow
Use of weak cryptographic key
Weak encryption
User-controlled bypass of sensitive method
Weak encryption: inadequate RSA padding
User-controlled data used in permissions   check
Wrong type of arguments to formatting   function
Open URL redirect
XML injection
Weak encryption: Insufficient key size
Suspicious add with sizeof
XML external entity expansion
XML internal entity expansion
Missing global error handler
Type confusion through parameter tampering
Too few arguments to formatting function
Stored cross-site scripting
Log entries created from user input
Improper control of generation of code
Failure to use secure cookies
Cast from char* to wchar_t*
Binding a socket to all network interfaces
CGI script vulnerable to cross-site   scripting
Exposed Spring Boot actuators
'requireSSL' attribute is not set to true
Header checking disabled
Accepting unknown SSH host keys when using   Paramiko
Bad redirect check
Clear-text storage of sensitive information
Insecure temporary file
Cleartext storage of sensitive information   in cookie
Enabling Electron   allowRunningInsecureContent
Client-side cross-site scripting
Failure to abandon session
Client-side URL redirect
Hard-coded connection string with   credentials
Arbitrary file write during archive   extraction (Zip Slip)
HTTP response splitting
Command built from user-controlled sources
Bad check for overflow of integer addition
Comparison of narrow type with wide type in   loop condition
Incorrect suffix check
Cookie security: overly broad domain
Information exposure through transmitted   data
Cookie security: overly broad path
JNDI lookup with user-controlled name
Cookie security: persistent cookie
Double escaping or unescaping
CORS misconfiguration for credentials   transfer
Encryption using ECB
Creating an ASP.NET debug binary may reveal   sensitive information
Exposure of private information
'input' function used in Python 2
Failure to use HTTPS or SFTP URL in Maven   artifact upload/download
Cross-window communication with unrestricted   target origin
Flask app is run in debug mode
Dangerous use of 'cin'
Assembly path injection
ASP.NET config file enables directory   browsing
Host header poisoning in email generation
Default version of SSL/TLS may be insecure
Implicit narrowing conversion in compound   assignment
Denial of Service from comparison of user   input against expensive regex
Incomplete HTML attribute sanitization
Deserialization of untrusted data
Incomplete string escaping or encoding
Loop bound injection
Badly bounded write
Deserialized delegate
Inefficient regular expression
Deserializing untrusted input
Building a command line with string   concatenation
Disabled Netty HTTP header validation
Call to alloca in a loop
Disabled Spring CSRF protection
Insecure URL whitelist
Disabled TLS certificate check
Call to function with fewer arguments than   declared parameters
Disabling Electron webSecurity
Cast between HRESULT and a Boolean type
Disabling SCE
Mismatching new/free or malloc/delete

</details>

**Comment by mseeger** [comment]
@jhutchings1 When are these checks run? Are they run as part of CI for every pull request? Or only now and then? If they fail, do they block the PR?

If these checks are blocking, we'd first want to make sure they "make sense"

**Comment by jhutchings1** [comment]
@mseeger The default configuration runs these as part of CI for every PR, yes. When it detects an error, it will create a failing check. Any admin or person with write permission could resolve the alert after triaging it though.

**Comment by szha** [comment]
Job PR-503-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-503/2/index.html

**Comment by mseeger** [comment]
@jhutchings1 OK, then did you run these checks on the current codebase? Do they currently pass?

**Comment by jhutchings1** [comment]
@mseeger The default set of queries look for a number of common security failures, and these show that you're clean (congrats!).

**Pull request merged**
