### PR TITLE
[Bugfix] Fix the problem that the specified feature_columns will be ignored

### PR DESCRIPTION
**Pull request by sxjscience**
*Issue #, if available:* https://github.com/awslabs/autogluon/issues/647

*Description of changes:*

- [x] Fix the issue that the specified feature columns will be ignored.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-653-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-653/1/index.html

**Comment by szha** [comment]
Job PR-653-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-653/2/index.html

**Review by jwmueller — APPROVED** [review]
LGTM.  Maybe there could also be another assert/check added here:  https://github.com/awslabs/autogluon/blob/353c5725c0d665cc82a2fd4cf85ffa626a09d5db/autogluon/task/text_prediction/text_prediction.py#L331

to ensure that each `col` in `feature_columns` actually appears in `train_data`.

**Comment by szha** [comment]
Job PR-653-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-653/3/index.html

**Pull request merged**
