### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by Innixma**
*Issue #, if available:*

*Description of changes:*

- Update badges, add badges to doc website
- Add link to Windows GitHub issue for Windows install instructions
- Update website main page example to be runnable
- Fixed documentation of Tabular NN models
- Added VowpalWabbit to autogluon.tabular.models documentation
- Re-ordered `Text, Image, and Tabular Data` to `Image, Text, and Tabular Data` as it flows nicer.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-1528-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1528/1/index.html

**Review by yinweisu — APPROVED** [review]
LGTM!

**Comment by Innixma** [comment]
TODO:

- [ ] Fix [formatting on front page](http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1528/1/index.html), for some reason banners are stacked vertically rather than being on one horizontal line.

**Comment by szha** [comment]
Job PR-1528-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1528/3/index.html

**Pull request merged**
