### PR TITLE
Added warnings to TextClassification usage

### PR DESCRIPTION
**Pull request by Innixma**
*Issue #, if available:*

*Description of changes:*

Added warnings to TextClassification usage

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by zhanghang1989** [comment]
We do have multiple supported dataset. Why should we add this warning? 
https://github.com/awslabs/autogluon/blob/master/autogluon/task/text_classification/dataset.py#L12-L13

**Comment by szha** [comment]
Job PR-267-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-267/1/index.html

**Comment by Innixma** [comment]
Ok, but we don't have support for a custom dataset right? That should definitely have a warning with it until it is resolved.

**Comment by zhanghang1989** [comment]
A GluonNLP intern will work on the custom dataset. 
You may put a warning for not supporting custom dataset for now.

**Comment by szha** [comment]
Job PR-267-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-267/2/index.html

**Pull request merged**
