### PR TITLE
Fix bfloat16 support + Fix documentation

### PR DESCRIPTION
**Pull request by sxjscience**
*Description of changes:*

- Fix bfloat16. Now we will automatically switch to 32 if bfloat16 is not supported.
- Add a `enable_progress_bar` flag and an environmental variable "AUTOMM_DISABLE_PROGRESS_BAR" to disable progress bar.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-1578-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1578/3/index.html

**Comment by szha** [comment]
Job PR-1578-7 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1578/7/index.html

**Comment by sxjscience** [comment]
Testing for bf16 support will require P4 instance. I've manually verified the correctness.

**Review by zhiqiangdon — APPROVED** [review]

**Comment by szha** [comment]
Job PR-1578-8 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1578/8/index.html

**Pull request merged**
