### PR TITLE
Remove MXNet dependencies from core

### PR DESCRIPTION
**Pull request by mseeger**
*Issue #, if available:*

*Description of changes:*
This is #721 after rebase

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mseeger** [comment]
E               RuntimeError: Failed downloading url https://autogluon.s3.amazonaws.com/numcomp/branin_200_data.pickle

@jwmueller This is one of the files you have replaced. Are you sure this went well?

**Comment by mseeger** [comment]
8c8590230e3b:~ matthis$ wget https://autogluon.s3.amazonaws.com/numcomp/branin_200_data.pickle
--2020-10-22 16:00:08--  https://autogluon.s3.amazonaws.com/numcomp/branin_200_data.pickle
Resolving autogluon.s3.amazonaws.com (autogluon.s3.amazonaws.com)... 52.218.232.138
Connecting to autogluon.s3.amazonaws.com (autogluon.s3.amazonaws.com)|52.218.232.138|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-10-22 16:00:10 ERROR 403: Forbidden.

@jwmueller This worked for me yesterday. Maybe some access rights changed?

**Comment by szha** [comment]
Job PR-726-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-726/3/index.html

**Comment by zhreshold** [comment]
> 8c8590230e3b:~ matthis$ wget https://autogluon.s3.amazonaws.com/numcomp/branin_200_data.pickle
> --2020-10-22 16:00:08-- https://autogluon.s3.amazonaws.com/numcomp/branin_200_data.pickle
> Resolving autogluon.s3.amazonaws.com (autogluon.s3.amazonaws.com)... 52.218.232.138
> Connecting to autogluon.s3.amazonaws.com (autogluon.s3.amazonaws.com)|52.218.232.138|:443... connected.
> HTTP request sent, awaiting response... 403 Forbidden
> 2020-10-22 16:00:10 ERROR 403: Forbidden.
> 
> @jwmueller This worked for me yesterday. Maybe some access rights changed?

The link works again

**Comment by jwmueller** [comment]
Yes there was permissions issue, but it's been fixed now

**Comment by szha** [comment]
Job PR-726-6 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-726/6/index.html

**Comment by szha** [comment]
Job PR-726-7 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-726/7/index.html

**Comment by mseeger** [comment]
What is missing here, is changes to Jenkinsfile, and also to how pip install etc works, such that mxnet is not required anymore when only core is installed.

**Comment by Innixma** [comment]
> What is missing here, is changes to Jenkinsfile, and also to how pip install etc works, such that mxnet is not required anymore when only core is installed.

I think that can be done in a follow-up PR

**Review by Innixma — APPROVED** [review]
LGTM! Will await another reviewer to approve and merge since I am not as familiar with how MXNet is used in the other tasks.

**Comment by szha** [comment]
Job PR-726-8 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-726/8/index.html

**Review by daveharmon — APPROVED** [review]

**Pull request merged**
