### PR TITLE
scd

### PR DESCRIPTION
**Pull request by yinweisu**
*Description of changes:*
This pr adds the ability to do chatOPs within our repo. After this pr is merged, we will be able to trigger macos and windows tests by comments, for example: https://github.com/yinweisu/hello-github-actions/pull/15.
This workflow needs to be merged to master branch to take effect. However, the following pr containing platform tests can be tested on a different branch

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by Innixma — APPROVED** [review]
LGTM, maybe add some kind of maintainer readme file that describes how to trigger these commands? Perhaps can be added in CONTRIBUTING.md

**Comment by yinweisu** [comment]
I can add the readme in the following pr. This pr alone is not enough to achieve the functionality

**Comment by szha** [comment]
Job PR-1461-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1461/3/index.html

**Comment by szha** [comment]
Job PR-1461-5 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1461/5/index.html

**Pull request merged**
