### PR TITLE
Update tutorial links

### PR DESCRIPTION
**Pull request by bryanyzhu**
*Issue #, if available:*
NA

*Description of changes:*
Update some hyperlinks. And change python file link to raw content link, so that users can directly download or copy the link.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sxjscience** [comment]
LGTM but I noticed that our index page is not fixed yet.

**Comment by bryanyzhu** [comment]
> LGTM but I noticed that our index page is not fixed yet.

Yes, the PR https://github.com/awslabs/autogluon/pull/2380 is currently running, will merge once it passes CI.

**Review by zhiqiangdon — APPROVED** [review]
LGTM

**Review by FANGAreNotGnu — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
