### PR TITLE
Single image predict

### LINKED ISSUE #233: Different classification，predict classification result is same，and probability is 1       按照官网的示例，使用训练出的模型预测两张不同分类的图片，预测结果不符合预期，类别结果错误，准确率1
image
image

### PR DESCRIPTION
**Pull request by aptsunny**
*Issue #, if available:*

bug fix #233 
use "mx.image.imread" instead of "PIL".
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-270-4 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-270/4/index.html

**Comment by szha** [comment]
Job PR-270-5 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-270/5/index.html

**Comment by szha** [comment]
Job PR-270-7 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-270/7/index.html

**Comment by szha** [comment]
Job PR-270-8 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-270/8/index.html

**Comment by szha** [comment]
Job PR-270-9 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-270/9/index.html

**Comment by szha** [comment]
Job PR-270-10 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-270/10/index.html

**Comment by 471899214** [comment]
the issue is still existed ,so how do i fix it?

**Comment by aptsunny** [comment]
> the issue is still existed ,so how do i fix it?

Actually, this issue has been solved by other pr. Maybe you are concerned about the wrong classification results on the tutorial. In fact, because the ci limits the training time, the single image prediction proformance will not be very good. but if the epoch is set more, I believe almost all the images in dataset will be classified correctly.

**Pull request closed without merging**
