### PR TITLE
updated version to v0.1.0

### PR DESCRIPTION
**Pull request by Innixma**
*Issue #, if available:*

*Description of changes:*

- [x] Updated version to v0.1.0
- [x] Added extra setup.py arguments
- [x] Removed mxnet hard dependency from autogluon.core and autogluon.tabular
- [x] Removed gluoncv hard dependency from autogluon.tabular

This will update the nightly pre-releases to use v0.1.0 instead of v0.0.16

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-906-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-906/1/index.html

**Comment by szha** [comment]
Job PR-906-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-906/2/index.html

**Comment by szha** [comment]
Job PR-906-7 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-906/7/index.html

**Comment by szha** [comment]
Job PR-906-9 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-906/9/index.html

**Comment by Innixma** [comment]
Benchmark results show that this is equal or better than current mainline, with no failures.

**Review by gradientsky — APPROVED** [review]

**Pull request merged**
