### PR TITLE
Ray parallel

### PR DESCRIPTION
**Pull request by yinweisu**
*Issue #, if available:*

*Description of changes:*
Added support for training folds in parallel.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yinweisu** [comment]
@Innixma @gradientsky CI has passed. Should be ready for review

**Comment by szha** [comment]
Job PR-1329-13 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1329/13/index.html

**Comment by szha** [comment]
Job PR-1329-19 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1329/19/index.html

**Comment by szha** [comment]
Job PR-1329-25 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1329/25/index.html

**Comment by szha** [comment]
Job PR-1329-28 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1329/28/index.html

**Comment by szha** [comment]
Job PR-1329-29 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1329/29/index.html

**Comment by szha** [comment]
Job PR-1329-34 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1329/34/index.html

**Comment by szha** [comment]
Job PR-1329-40 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1329/40/index.html

**Comment by szha** [comment]
Job PR-1329-41 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1329/41/index.html

**Comment by Innixma** [comment]
LGTM, amazing work @yinweisu !

**Pull request merged**
