### PR TITLE
Refactoring and bug fixes

### PR DESCRIPTION
**Pull request by mseeger**
*Issue #, if available:*

*Description of changes:*
Some refactoring and bug fixes from recent work on the HPO part

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-918-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-918/1/index.html

**Comment by mseeger** [comment]
Some more details on this one:
- Fixed issue with training_history callback mechanism, used to store results regularly while an experiment is running
- Added a more direct way to create a bayesopt searcher for FIFO scheduling
- Simplified internal profiling code

Paving the way for more to come.

**Comment by mseeger** [comment]
Will reopen with more changes

**Comment by Innixma** [comment]
@mseeger do you think it makes sense to get this in by v0.1 or after v0.1? How easy will it be to test and ensure we didn't add any major defects?

**Pull request closed without merging**
