### PR TITLE
[WIP]Add cheat sheet to website

### PR DESCRIPTION
**Pull request by yinweisu**
*Issue #, if available:*

*Description of changes:*
Add cheat sheet to our documentation site.
Inserting html directly results in weird format. Use a combination of image and link to pdf instead.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-1605-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1605/1/index.html

**Comment by szha** [comment]
Job PR-1605-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1605/2/index.html

**Review by Innixma — APPROVED** [review]
LGTM, this is great!

**Comment by Innixma** [comment]
@yinweisu can you also push this commit to the `stable` and `0.4.0` branches? This will ensure that this shows up in our stable docs.

**Pull request merged**
