### PR TITLE
Various bug fixes

### PR DESCRIPTION
**Pull request by mseeger**
*Issue #, if available:*

*Description of changes:*
- Various bug fixes (for example, in kernel computation code)
- Simplifications and small extensions

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-849-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-849/2/index.html

**Review by sxjscience — APPROVED** [review]
The change looks good to me. However, I'm not fully clear about the usage of some APIs and it would be better if we can later add some documentations. In addition, we lack test cases for this part.

**Comment by mseeger** [comment]
Thanks @sxjscience ! I will add some docstrings. I am currently working on a larger topic, for which some of these changes here are needed, but they are in general bug fixes and simplifications.

**Comment by szha** [comment]
Job PR-849-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-849/3/index.html

**Pull request merged**
