### PR TITLE
Replace models in detection test to a smaller one.

### PR DESCRIPTION
**Pull request by FANGAreNotGnu**
Changed cascade_rcnn_x101 to mask_rcnn_r50 in detection test to avoid the occasional error if the downloading model size is too large.

Also changed mim install timeout value from default (15s) to 120s.

TODO: Fix missing config contents in centernet (test_pipeline.image_scale) and ssd (mean, std) in next pr.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by FANGAreNotGnu** [comment]
While "mim install mmcv-full", there is a read timeout. Shall I rerun the checks or is there a way to fix it? @bryanyzhu  @zhiqiangdon

**Comment by zhiqiangdon** [comment]
> While "mim install mmcv-full", there is a read timeout. Shall I rerun the checks or is there a way to fix it? @bryanyzhu @zhiqiangdon

Try to rerun the CI job.

**Comment by bryanyzhu** [comment]
> While "mim install mmcv-full", there is a read timeout. Shall I rerun the checks or is there a way to fix it? @bryanyzhu @zhiqiangdon

You can add a longer timeout to mim install like `mim install mmcv-full --default-timeout 1000`, but I agree with @zhiqiangdon that rerun CI is an easier choice.

**Review by zhiqiangdon — APPROVED** [review]
LGTM! Thanks!

**Review by suzhoum — APPROVED** [review]
LGTM!

**Pull request merged**
