### PR TITLE
Update to v0.4.0

### PR DESCRIPTION
**Pull request by Innixma**
*Issue #, if available:*

*Description of changes:*

- Update version to v0.4.0
- Will merge once ready to release.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-1589-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1589/1/index.html

**Comment by szha** [comment]
Job PR-1589-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1589/3/index.html

**Comment by gradientsky** [comment]
Missing updates in https://github.com/awslabs/autogluon/blob/master/tabular/src/autogluon/tabular/predictor/predictor.py#L2812

**Comment by Innixma** [comment]
> 



> Missing updates in https://github.com/awslabs/autogluon/blob/master/tabular/src/autogluon/tabular/predictor/predictor.py#L2812

No, this is correct. Version caching wasn't implemented until v0.3.1, that is what the warning is referring to.

**Comment by Innixma** [comment]
> 



> Missing updates in https://github.com/awslabs/autogluon/blob/master/tabular/src/autogluon/tabular/predictor/predictor.py#L2812

No, this is correct. Version caching wasn't implemented until v0.3.1, that is what the warning is referring to.

**Review by gradientsky — APPROVED** [review]

**Pull request merged**
