### PR TITLE
Refactor AutoMM's utils

### PR DESCRIPTION
**Pull request by zhiqiangdon**
As AutoMM is integrating more and more functionalities, the utils of predictor keep increasing. To reduce one over-long util file, we may need to refactor it by splitting it into smaller files.

1. Create a new `utils` directory.
2. Split utils into categories: `data`, `model`, `checkpoint`, `save`, `load`, `environment`, `config`, `pipeline`, `download`, `object_detection`, `inference`, `metric`, `log`, and `misc`. Reference: https://github.com/rwightman/pytorch-image-models/tree/master/timm/utils

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by bryanyzhu — APPROVED** [review]
Awesome, looks good.

**Review by FANGAreNotGnu — APPROVED** [review]
LGTM, thanks!

**Review by suzhoum — APPROVED** [review]
LGTM! 🥇

**Review by sxjscience — APPROVED** [review]
LGTM

**Pull request merged**
