### PR TITLE
Add More Numerical Embedding Methods for Numerical Transformer in AutoMM

### PR DESCRIPTION
**Pull request by yiqings**
*Issue #, if available:*

*Description of changes:*

Add Numerical Embeddings described in [On Embeddings for Numerical Features in Tabular Deep Learning](https://arxiv.org/pdf/2203.05556.pdf) to AutoMM.

We add `embedding_arch` in the `numerical_transformer` flag and support the combination of a bunch of flags. This helps us support the embedding functions mentioned in [Table 3](https://arxiv.org/pdf/2203.05556.pdf).

Examples using override `hyperparameters` flag in `AutoMMPredictor` for various embedding schemes are summarized as follows:

```
- L
   - model.numerical_transformer.embedding_arch=['linear']
- LR
   - model.numerical_transformer.embedding_arch=['linear', 'relu']
- LRLR
   - model.numerical_transformer.embedding_arch=['linear', 'relu', 'linear', 'relu']
- P
   - model.numerical_transformer.embedding_arch=['positional']
- PL
   - model.numerical_transformer.embedding_arch=['positional', 'linear']
- PLR
   - model.numerical_transformer.embedding_arch=['positional', 'linear', 'relu']
- PLRLR
   - model.numerical_transformer.embedding_arch=['positional', 'linear', 'relu', 'linear', 'relu']
- AutoDis
   - model.numerical_transformer.embedding_arch=['autodis']
```

Notably, in `L` (i.e. model.numerical_transformer.embedding_arch=['linear']) for `numerical transformer`, it is reduced to the original feature_tokenzier in [FT_Transformer](https://proceedings.neurips.cc/paper/2021/file/9d86d83f925f2149e9edb0ac3b49229c-Paper.pdf) (Figure 2a).

We currently use the `LR` (i.e.  model.numerical_transformer.embedding_arch=['linear', 'relu']) as default. It is shown to be better than `L` in [Tabule 2](https://arxiv.org/pdf/2203.05556.pdf) with no extra computational cost.

ToDo:
1. ~~Refine codes and annotations.~~
2. ~~Expose hyper-parameters to `create_model` and `model_config`.~~
3. ~~Update unit test.~~
4. Evaluations. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-1732-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1732/1/index.html

**Comment by szha** [comment]
Job PR-1732-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1732/2/index.html

**Comment by szha** [comment]
Job PR-1732-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1732/3/index.html

**Comment by szha** [comment]
Job PR-1732-4 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1732/4/index.html

**Comment by szha** [comment]
Job PR-1732-6 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1732/6/index.html

**Review by sxjscience — APPROVED** [review]
LGTM

**Comment by szha** [comment]
Job PR-1732-9 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1732/9/index.html

**Comment by szha** [comment]
Job PR-1732-10 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1732/10/index.html

**Comment by szha** [comment]
Job PR-1732-11 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1732/11/index.html

**Comment by szha** [comment]
Job PR-1732-12 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1732/12/index.html

**Comment by yiqings** [comment]
Hi @sxjscience @zhiqiangdon, this PR is ready for review.

**Comment by szha** [comment]
Job PR-1732-13 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1732/13/index.html

**Comment by szha** [comment]
Job PR-1732-14 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1732/14/index.html

**Pull request merged**
