### PR TITLE
[Text Fix] Fix the competition link + Fix docs

### PR DESCRIPTION
**Pull request by sxjscience**
Somehow the MachineHack competitions cannot be directly accessed via the link and we must provide the instruction about how to go to the page.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-963-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-963/1/index.html

**Comment by szha** [comment]
Job PR-963-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-963/2/index.html

**Comment by szha** [comment]
Job PR-963-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-963/3/index.html

**Comment by szha** [comment]
Job PR-963-6 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-963/6/index.html

**Review by jwmueller — APPROVED** [review]

**Pull request merged**
