### PR TITLE
[WIP] Try fixing text CI memory issue

### PR DESCRIPTION
**Pull request by yinweisu**
*Issue #, if available:*

*Description of changes:*
Try fixing text CI memory issue

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sxjscience** [comment]
Find that the unittest has passed but it shows another error when building the tutorial.

**Comment by yinweisu** [comment]
> Find that the unittest has passed but it shows another error when building the tutorial.

That's just me manually cancelling the run because it has passed the unit test and I want to run it again to double check :).

**Comment by yinweisu** [comment]
The text has passed the CI in three consecutive runs. Though not proving this fix the issue, but worth giving it a shot by merging it in. @sxjscience @Innixma @gradientsky

**Review by Innixma — APPROVED** [review]
LGTM!

**Pull request merged**
