### PR TITLE
[Release 0.6] [Multimodal] Check if folder is empty before raise

### PR DESCRIPTION
**Pull request by yinweisu**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by gradientsky — APPROVED** [review]

**Review by zhiqiangdon — APPROVED** [review]
LGTM!

**Review by FANGAreNotGnu — APPROVED** [review]
LGTM, we can also detect if there is a ckpt file. But either way if two programs are using the same path, it may not be detected.

**Review by Innixma — APPROVED** [review]
LGTM!

**Comment by yinweisu** [comment]
Unit tests passed. Will merge....

**Pull request merged**
