### PR TITLE
Tabular: Added documentation of AbstractModel

### PR DESCRIPTION
**Pull request by Innixma**
*Issue #, if available:*

*Description of changes:*

- Added documentation for AbstractModel
- Reduced logging verbosity of TextPredictor when used in Tabular.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-966-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-966/1/index.html

**Review by jwmueller — APPROVED** [review]
One thing that could be added to docs of AbstractModel that will help contributors:

what are some general preprocessing steps that are still needed for the internal form of the data received by `fit()`. I suspect many contributors may think the data are 100% processed, but they are not at that point.  Eg. could say: "The internal form of the data passed into `model.fit()` is only partially processed, certain models may require further processing such as handling of missing values, rescaling of continuous features, etc."

**Comment by Innixma** [comment]
> One thing that could be added to docs of AbstractModel that will help contributors:
> 
> what are some general preprocessing steps that are still needed for the internal form of the data received by `fit()`. I suspect many contributors may think the data are 100% processed, but they are not at that point. Eg. could say: "The internal form of the data passed into `model.fit()` is only partially processed, certain models may require further processing such as handling of missing values, rescaling of continuous features, etc."

Added

**Comment by szha** [comment]
Job PR-966-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-966/2/index.html

**Pull request merged**
