### PR TITLE
FIX: basic pep8 fixes

### PR DESCRIPTION
**Pull request by razmikmelikbekyan**
*Issue #, if available:*

*Description of changes:*
Basic PEP8 fixes.
String formatting. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-308-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-308/1/index.html

**Comment by szha** [comment]
Job PR-308-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-308/2/index.html

**Comment by Innixma** [comment]
@zhanghang1989 Can you please take a look?

**Comment by zhanghang1989** [comment]
Thanks @Innixma This PR only improves the coding style and looks good to me.

**Pull request merged**
