### PR TITLE
fix hpo issue for NER

### PR DESCRIPTION
**Pull request by cheungdaven**
*Issue #, if available:*

*Description of changes:*

Fix the dataprocessor nonetype issue 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sxjscience** [comment]
Do we need to add a test-case?

**Comment by cheungdaven** [comment]
> Do we need to add a test-case?

sure, will do that.

**Review by sxjscience — APPROVED** [review]
LGTM

**Review by bryanyzhu — APPROVED** [review]
LGTM.

**Pull request merged**
