### PR TITLE
Reduce nesting

### PR DESCRIPTION
**Pull request by daikikatsuragawa**
It corresponds to the comment "TODO: Hack".

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-795-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-795/1/index.html

**Comment by daikikatsuragawa** [comment]
There was a conflict, so it was resolved.

**Comment by szha** [comment]
Job PR-795-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-795/2/index.html

**Review by Innixma — COMMENTED** [review]
Thanks for the contribution! Please see my comment as I believe this is being handled in an existing PR.

**Comment by Innixma** [comment]
#794 has been merged in and the TODOs have been resolved, closing this for now.

**Comment by daikikatsuragawa** [comment]
No, I'm sorry I misunderstood.

Thank you for the closing decision.

**Pull request closed without merging**
