### PR TITLE
Fixed model save and load path with uuid for multiple runs

### PR DESCRIPTION
**Pull request by tonyhoo**
*Issue #, if available:*
Currently, model load and save with hard coded filename which is prone to error for multiple runs

*Description of changes:*

Added UUID to the model_path in case of multiple runs

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by bryanyzhu — APPROVED** [review]
LGTM. Can you exclude`beginner_img_cls` here? I already added more changes in PR #2411  Thank you.

**Comment by tonyhoo** [comment]
> LGTM. Can you exclude`beginner_img_cls` here? I already added more changes in PR #2411 Thank you.

Done

**Review by suzhoum — APPROVED** [review]
LGTM!

**Review by sxjscience — APPROVED** [review]
LGTM!

**Pull request merged**
