### PR TITLE
Improve image-to-image matching tutorial

### PR DESCRIPTION
**Pull request by zhiqiangdon**
*Issue #, if available:*

*Description of changes:*

1. Make image-to-image tutorial online runnable.
2. Fix the match_label docstring.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by bryanyzhu — APPROVED** [review]
LGTM, thank you for making it runnable.

**Review by suzhoum — APPROVED** [review]
LGTM！

**Review by cheungdaven — APPROVED** [review]
LGTM!

**Review by sxjscience — APPROVED** [review]
LGTM

**Pull request merged**
