### PR TITLE
Support distillation for text predictor and add default for distiller

### PR DESCRIPTION
**Pull request by zhiqiangdon**
1. Support distillation for the text predictor.
2. Previous adding default for distill is not optimal. This is to improve the design.
3. Add unit tests for passing a predictor object or a a predictor path.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-1895-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1895/1/index.html

**Review by sxjscience — APPROVED** [review]
LGTM

**Review by bryanyzhu — APPROVED** [review]
LGTM

**Comment by szha** [comment]
Job PR-1895-4 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1895/4/index.html

**Pull request merged**
