### PR TITLE
Tabular: Added tie_breaker options for EnsembleSelection, defaulted to 'second_metric'

### PR DESCRIPTION
**Pull request by Innixma**
*Issue #, if available:*

*Description of changes:*

- Added tie_breaker options for EnsembleSelection, defaulted to 'second_metric'

Next Steps:

- [x] Benchmark PR to ensure quality has not degraded.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-913-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-913/1/index.html

**Comment by szha** [comment]
Job PR-913-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-913/2/index.html

**Review by gradientsky — APPROVED** [review]

**Comment by szha** [comment]
Job PR-913-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-913/3/index.html

**Comment by szha** [comment]
Job PR-913-4 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-913/4/index.html

**Pull request merged**
