### PR TITLE
Add tabular tests dependency to platform test

### PR DESCRIPTION
**Pull request by yinweisu**
*Issue #, if available:*

*Description of changes:*
* Add tabular[tests] dependency to platform tests
* Fixed tensor type on windows

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yinweisu** [comment]
TorchNN fails on Windows

**Comment by szha** [comment]
Job PR-1506-4 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1506/4/index.html

**Review by Innixma — APPROVED** [review]
LGTM!

**Pull request merged**
