### PR TITLE
Distributed Remote fix and SageMaker Utils

### PR DESCRIPTION
**Pull request by zhanghang1989**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-152-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-152/1/index.html

**Comment by szha** [comment]
Job PR-152-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-152/3/index.html

**Comment by szha** [comment]
Job PR-152-4 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-152/4/index.html

**Comment by szha** [comment]
Job PR-152-5 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-152/5/index.html

**Comment by szha** [comment]
Job PR-152-6 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-152/6/index.html

**Comment by mseeger** [comment]
Should Anton Chernov know about this?

**Comment by zhanghang1989** [comment]
> Anton Chernov should know about this?

Thanks Matthias! 
Hi @lebeg , FYI this PR fix issue during distributed traing and work with `AutoGluon-Docker` repo I shared with you via GitHub.

**Pull request merged**
