### PR TITLE
add standford dog pretrained models

### PR DESCRIPTION
**Pull request by zhanghang1989**
*Issue #, if available:*

fixes https://github.com/awslabs/autogluon/issues/158

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-236-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-236/3/index.html

**Comment by szha** [comment]
Job PR-236-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-236/2/index.html

**Comment by szha** [comment]
Job PR-236-4 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-236/4/index.html

**Comment by szha** [comment]
Job PR-236-5 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-236/5/index.html

**Comment by szha** [comment]
Job PR-236-6 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-236/6/index.html

**Comment by aptsunny** [comment]
i test my script with pretrain model right now @zhanghang1989

**Pull request merged**
