### PR TITLE
[Security] pickle security improvements

### PR DESCRIPTION
**Pull request by gradientsky**
*Issue #, if available:*
#885 - modified version, addressing issues with broken functionality

*Description of changes:*
Security Fix for Arbitrary Code Execution. This change improves pickle security vulnerability handling.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-911-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-911/3/index.html

**Comment by szha** [comment]
Job PR-911-4 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-911/4/index.html

**Review by Anon-Artist — COMMENTED** [review]
Nice Catch

**Comment by stonehead8111** [comment]
https://github.com/awslabs/autogluon/pull/1355#discussion_r737712000

**Comment by stonehead8111** [comment]
https://github.com/awslabs/autogluon/pull/1355#discussion_r737712000

**Pull request closed without merging**
