### PR TITLE
add Faster RCNN to autogluon

### PR DESCRIPTION
**Pull request by Jerryzcn**
Add Faster RCNN to autogluon.
Training, validation and eval are tested

### CODE REVIEW

**Comment by szha** [comment]
Job PR-290-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-290/2/index.html

**Comment by szha** [comment]
Job PR-290-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-290/3/index.html

**Comment by szha** [comment]
Job PR-290-4 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-290/4/index.html

**Comment by szha** [comment]
Job PR-290-5 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-290/5/index.html

**Comment by szha** [comment]
Job PR-290-6 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-290/6/index.html

**Comment by zhanghang1989** [comment]
@chongruo could you review this PR at your convenience?

**Pull request merged**
