### PR TITLE
update pandas

### PR DESCRIPTION
**Pull request by flozi00**
old version has bug
https://stackoverflow.com/questions/57226917/unboundlocalerror-local-variable-arith-flex-referenced-before-assignment

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-191-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-191/1/index.html

**Comment by Innixma** [comment]
Has this bug impacted AutoGluon? I would be willing to increase the version but will first have to do further testing to ensure nothing breaks.

**Comment by flozi00** [comment]
I ran all the examples and it worked

**Comment by Innixma** [comment]
I think the following would work best:

pandas>=0.24.2,<=0.25.3

Could you update the PR to this?

Also, could you describe your system? I have not had issues in AutoGluon with pandas 0.24.2 on Mac or Linux.

**Comment by flozi00** [comment]
The machine is Ubuntu 19 running in virtualbox.

**Comment by szha** [comment]
Job PR-191-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-191/3/index.html

**Comment by Innixma** [comment]
Thanks again for this PR! I will plan to merge it once I have tested it on various datasets to ensure performance regressions are not present.

**Comment by szha** [comment]
Job PR-191-4 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-191/4/index.html

**Pull request closed without merging**
