### PR TITLE
[Bugfix] Fix text augmentation + Change the default label scaler to standardscaler

### PR DESCRIPTION
**Pull request by sxjscience**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sxjscience** [comment]
@Linuxdex The previous PR https://github.com/awslabs/autogluon/pull/1777 changed the default value of numerical_label_scaler.

**Comment by szha** [comment]
Job PR-1807-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1807/2/index.html

**Comment by szha** [comment]
Job PR-1807-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1807/3/index.html

**Review by bryanyzhu — APPROVED** [review]
LGTM

**Pull request merged**
