### PR TITLE
Mac patch gpu

### PR DESCRIPTION
**Pull request by zhanghang1989**
*Issue #, if available:*

closes https://github.com/awslabs/autogluon/pull/117

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-145-5 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-145/5/index.html

**Comment by szha** [comment]
Job PR-145-6 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-145/6/index.html

**Comment by Innixma** [comment]
@zhanghang1989 Can you confirm if there are any remaining steps needed for this PR and the decision whether to merge it or not? If we have decided not to merge it, we should close it since this PR has been open for some time.

**Comment by zhanghang1989** [comment]
Thanks @Innixma . I am closing it, since I haven't tested the code recently.

**Pull request closed without merging**
