### PR TITLE
Tabular: Improved readability and testability of BaggedEnsembleModel._fit_folds

### PR DESCRIPTION
**Pull request by Innixma**
*Issue #, if available:*

*Description of changes:*

- Improved method structure
- Moved initialization and passing of fold configs of fold fitting strategy to after the creation of the configs, rather than during the creation of the configs.
- Added assert statement to ensure expected number of fold models are being trained.
- Fixed minor bug where `is_last_fold` was the opposite value it should have been for all configs.
- Added unit test to sanity check configs are generally correct. (A full unit test would be more complicated as it would require checking every kfold split in the configs.)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-1370-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1370/1/index.html

**Comment by szha** [comment]
Job PR-1370-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1370/2/index.html

**Comment by szha** [comment]
Job PR-1370-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1370/3/index.html

**Review by yinweisu — APPROVED** [review]
LGTM

**Pull request merged**
