### PR TITLE
Allow generic item indices in time series dataframe

### PR DESCRIPTION
**Pull request by canerturkmen**
*Issue #, if available:*

*Description of changes:*

~~**Depends on:** #1841 #1839~~

Removes the constraint of specifying only integer type item indices in time series panel data frames, improving user experience.

cc: @huibinshen 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-1849-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1849/1/index.html

**Comment by szha** [comment]
Job PR-1849-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1849/2/index.html

**Comment by huibinshen** [comment]
LGTM!

**Review by Innixma — APPROVED** [review]
LGTM!

**Pull request merged**
