### PR TITLE
Fix TimeSeriesDataFrame type inconsistencies

### PR DESCRIPTION
**Pull request by canerturkmen**
*Issue #, if available:*

*Description of changes:*

- Add convenience method and override `_constructor` in `TimeSeriesDataFrame`. This prevents type inconsistencies in DataFrame methods that return copies.
- Add `"label"` alias to Predictor.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by canerturkmen** [comment]
@huibinshen

**Comment by huibinshen** [comment]
LGTM!

**Review by Innixma — APPROVED** [review]
LGTM!

**Comment by szha** [comment]
Job PR-1778-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1778/3/index.html

**Comment by szha** [comment]
Job PR-1778-4 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1778/4/index.html

**Pull request merged**
