### PR TITLE
Relax some dependencies in setup.py to ease compatibility

### PR DESCRIPTION
**Pull request by larroy**
@lnnixma

### CODE REVIEW

**Comment by szha** [comment]
Job PR-242-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-242/1/index.html

**Comment by Innixma** [comment]
Lets plan to merge this for 0.1

**Comment by szha** [comment]
Job PR-242-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-242/2/index.html

**Comment by larroy** [comment]
Shall we merge this?

**Comment by szha** [comment]
Job PR-242-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-242/3/index.html

**Pull request merged**
