### PR TITLE
Improve converting input data to dataframe for AutoMM

### PR DESCRIPTION
**Pull request by zhiqiangdon**
1. Support input data in the `list` format, i.e., no column names are provided.
2. Check if the provided columns contain all the required columns.
3. Add unit tests.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-1891-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1891/1/index.html

**Review by sxjscience — APPROVED** [review]
LGTM!

**Review by bryanyzhu — APPROVED** [review]
Thanks for the PR.

**Comment by sxjscience** [comment]
@Innixma Should we start to merge feature improvement PRs to master? We may first merge these PRs but won't use them in the tutorials.

**Pull request merged**
