### PR TITLE
Support other metrics in score function of AbstractGluonTSModel

### PR DESCRIPTION
**Pull request by huibinshen**
*Issue #, if available:*

Support other metrics in score function of AbstractGluonTSModel.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-1782-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1782/1/index.html

**Comment by szha** [comment]
Job PR-1782-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1782/2/index.html

**Review by Innixma — APPROVED** [review]
LGTM!

**Review by canerturkmen — APPROVED** [review]
Thanks Huibin!

**Pull request merged**
