### PR TITLE
Fix mousouver plot after bokeh dropped previewsave

### PR DESCRIPTION
**Pull request by jwmueller**
Update mousoverplot to match bokeh update to v2.0.1 which dropped compatibility with previewsave tool.

### CODE REVIEW

**Comment by Innixma** [comment]
Will this fix work with older versions of bokeh? If not we should specify version requirements.

Also, this might break 0.0.5 and 0.0.6 for users. Do we want to do a version update to 0.0.7? How widespread is the impact?

**Comment by szha** [comment]
Job PR-389-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-389/1/index.html

**Comment by jwmueller** [comment]
Most older versions of bokeh should still work.  Note that bokeh is not currently a listed requirement, we currently just print a warning for the user to install bokeh when the lazy import fails.  I'll update this print statement to direct the user to install a specific bokeh version, so we don't run into this scenario again in the future.

I'm not sure we should install a particular bokeh version on the CI server though, it's in some ways good to be able to catch issues like this. 

I'm also not sure the backwards-incompatible bokeh update should force us to release autogluon  0.0.7 in response, since we don't specify bokeh as an official requirement.  Only the `fit_summary()` method used by various tasks' `Predictor` objects is broken as a result of the update.  I think a user who encounters this error can just downgrade their bokeh version and then recall `fit_summary()`, so all their computation expended during training is not wasted (will post a github issue to clarify this).

@zhanghang1989 any thoughts?

**Comment by jwmueller** [comment]
Issue to warn recent users of autogluon <= 0.0.6 about newest bokeh:  https://github.com/awslabs/autogluon/issues/390

**Pull request merged**
