### PR TITLE
Improve multilingual tutorial + Change default lr_decay to 0.9

### PR DESCRIPTION
**Pull request by sxjscience**
*Description of changes:*

Change the default lr_decay to 0.9 based on the internal HPO results.
Also, improve the tutorial about zero-shot cross lingual transfer.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-1586-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1586/1/index.html

**Comment by szha** [comment]
Job PR-1586-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1586/2/index.html

**Comment by szha** [comment]
Job PR-1586-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1586/3/index.html

**Comment by szha** [comment]
Job PR-1586-4 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1586/4/index.html

**Review by zhiqiangdon — APPROVED** [review]

**Pull request merged**
