### PR TITLE
Type Checking correction, indentation correction

### PR DESCRIPTION
**Pull request by razmikmelikbekyan**
*Issue #271 *

*Description of changes:*
- changing type checking for using `isinstance` 
- indentation correction
- replacing `set` creation from `list` to directly `set` creation

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-275-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-275/1/index.html

**Comment by razmikmelikbekyan** [comment]
Dear autogloun team,
I am reviewing the source codr of aoutgloun to understand how it works. And noticed that in many aspects code is a not clean enough interms of pep8 which is the python standard.  For correcting them do we need always to have a open issue ?

Regards,
Razmik 
 
  On Sat, 8 Feb 2020 at 12:11, Sheng Zha<notifications@github.com> wrote:   
Job PR-275-1 is done.
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-275/1/index.html

**Comment by Innixma** [comment]
Hi Razmik,

Thanks greatly for your help!

In regards to corrections, you do not need to open an issue first before sending a fix PR, but if you would like to open an issue for them, feel free. Note that we intentionally don't follow the max characters / line PEP8 standard, at least for the current time.

Best,
Nick

**Comment by razmikmelikbekyan** [comment]
Hi Nick, 
Thanks for response. 
I will continue contributing. 
Regards,
Razmik 
 
  On Mon, 10 Feb 2020 at 20:45, Nick Erickson<notifications@github.com> wrote:   
Hi Razmik,

Thanks greatly for your help!

In regards to corrections, you do not need to open an issue first before sending a fix PR, but if you would like to open an issue for them, feel free. Note that we intentionally don't follow the max characters / line PEP8 standard, at least for the current time.

Best,
Nick

**Pull request merged**
