### PR TITLE
Refactoring of FIFOScheduler, HyperbandScheduler: self.time_out bette…

### PR DESCRIPTION
**Pull request by mseeger**
…r respected by stopping jobs when they run over

*Issue #, if available:*

*Description of changes:*
Cleans up FIFOScheduler, HyperbandScheduler.

A change is that self.time_out is better respected now. Before this change, jobs were started until self.time_out is reached, but they were not stopped, so the experiment can run for much longer. With this change, whenever a job reports metrics, it is stopped if self.time_out is reached. This way, an experiment ends not much after self.time_out.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-1050-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1050/1/index.html

**Comment by szha** [comment]
Job PR-1050-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1050/2/index.html

**Comment by mseeger** [comment]
I feel you could really like this. Right now, if you set time_out, HPO may still run a lot longer. With this change, HPO will run about as long as time_out, so you get a better control.

**Comment by Innixma** [comment]
Thats nice to hear, I remember we had to essentially hack that functionality in before, so its good for it to be officially supported. @gradientsky could you do the initial review?

**Comment by szha** [comment]
Job PR-1050-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1050/3/index.html

**Review by gradientsky — APPROVED** [review]

**Comment by Innixma** [comment]
@mseeger Looks like @gradientsky doesn't have any concerns. Feel free to merge whenever you are ready.

**Comment by szha** [comment]
Job PR-1050-4 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1050/4/index.html

**Pull request merged**
