### PR TITLE
ARM/M1 dependency upgrade and doc

### PR DESCRIPTION
**Pull request by yinweisu**
*Issue #, if available:*
https://github.com/awslabs/autogluon/issues/1242
https://github.com/awslabs/autogluon/issues/1424

*Description of changes:*
* Upgrade scipy and ray to incoporate m1 support
* Add ARM/M1 installation faq

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-1503-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1503/3/index.html

**Comment by szha** [comment]
Job PR-1503-6 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1503/6/index.html

**Comment by szha** [comment]
Job PR-1503-7 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1503/7/index.html

**Comment by szha** [comment]
Job PR-1503-8 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1503/8/index.html

**Review by Innixma — APPROVED** [review]
LGTM!

**Pull request merged**
