### PR TITLE
Added optional dependencies

### PR DESCRIPTION
**Pull request by Innixma**
*Issue #, if available:*

*Description of changes:*

- Made xgboost, catboost, lightgbm, fastai, torch, and skopt optional

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-941-5 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-941/5/index.html

**Comment by szha** [comment]
Job PR-941-6 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-941/6/index.html

**Review by jwmueller — APPROVED** [review]
May consider adding section to Installation instructions FAQ that shows how to do minimal dependencies autogluon installation vs full installation.

**Comment by Innixma** [comment]
> May consider adding section to Installation instructions FAQ that shows how to do minimal dependencies autogluon installation vs full installation.

Definitely, this PR is primarily to test that it works as intended (Will be testing pypi over weekend), then will expand it out and update docs in follow-up PRs.

**Pull request merged**
