### PR TITLE
Fix NER best quality preset

### PR DESCRIPTION
**Pull request by cheungdaven**
*Issue #, if available:*

*Description of changes:*
Fix best quality ner preset

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by sxjscience — APPROVED** [review]
LGTM

**Comment by sxjscience** [comment]
@cheungdaven Do we need to use a smaller batch_size?

**Comment by cheungdaven** [comment]
> @cheungdaven Do we need to use a smaller batch_size?

fixed.

**Review by bryanyzhu — APPROVED** [review]
LGTM

**Review by zhiqiangdon — APPROVED** [review]
LGTM!

**Pull request merged**
