### PR TITLE
Add improved datapart helper

### PR DESCRIPTION
**Pull request by Pearcekieser**
*Issue #, if available:*
None.

*Description of changes:*
Adds a function and unit test for adding sequential and cyclic date features based on a pd.Series of datetime's.  In general functions map from Series -> DataFrame.

Sample use is demonstrated in the unit test

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-610-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-610/1/index.html

**Comment by Innixma** [comment]
Thanks for the contribution! I think its best if we wait for #584 to get merged before reviewing this. With #584 merged, you will be able to create a new FeatureGenerator which utilizes these functions so we can plug it into the feature generator to see how it performs.

**Comment by szha** [comment]
Job PR-610-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-610/2/index.html

**Comment by Innixma** [comment]
@Pearcekieser Thanks for your patience! Now that #584 is merged, could you refactor this PR such that you create a new FeatureGenerator class which extends AbstractFeatureGenerator? Please also add a unit test similar to those that exist for the other feature generators to make it easier for review and maintainability.

**Comment by szha** [comment]
Job PR-610-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-610/3/index.html

**Comment by szha** [comment]
Job PR-610-4 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-610/4/index.html

**Comment by szha** [comment]
Job PR-610-5 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-610/5/index.html

**Comment by Innixma** [comment]
Closing PR for now. Feel free to re-open if you are still interested in contributing this feature. Since a fair amount of time has passed, I would recommend opening up a github issue where we can discuss the preferred implementation approach.

**Pull request closed without merging**
