### PR TITLE
Support more datasets for object detection

### PR DESCRIPTION
**Pull request by chongruo**
support more datasets (clipart, watercolor, comic, voc) for object detection.

add running scripts

### CODE REVIEW

**Comment by szha** [comment]
Job PR-176-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-176/1/index.html

**Comment by szha** [comment]
Job PR-176-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-176/2/index.html

**Comment by jwmueller** [comment]
In the documentation, we need to have a text description of each dataset somewhere as well as the full list of dataset options.  Otherwise it's very opaque for a user to work with.

**Comment by szha** [comment]
Job PR-176-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-176/3/index.html

**Comment by zhanghang1989** [comment]
> In the documentation, we need to have a text description of each dataset somewhere as well as the full list of dataset options. Otherwise it's very opaque for a user to work with.

Agree. @chongruo Let's improve the documentation for object detection in next PR.

**Pull request merged**
