### PR TITLE
Text: Remove pyarrow

### PR DESCRIPTION
**Pull request by Innixma**
*Issue #, if available:*
#1053

*Description of changes:*

- Remove pyarrow dependency. Users can install pyarrow separately if they wish to load parquet files.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by crazy25000 — APPROVED** [review]
Thank you!

**Comment by szha** [comment]
Job PR-1200-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1200/1/index.html

**Review by jwmueller — COMMENTED** [review]
Will let @sxjscience review

**Review by sxjscience — APPROVED** [review]
LGTM

**Pull request merged**
