### PR TITLE
post-refactor corrections/improvements

### PR DESCRIPTION
**Pull request by jwmueller**

### CODE REVIEW

**Comment by szha** [comment]
Job PR-705-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-705/1/index.html

**Comment by szha** [comment]
Job PR-705-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-705/2/index.html

**Comment by szha** [comment]
Job PR-705-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-705/3/index.html

**Review by gradientsky — APPROVED** [review]

**Comment by szha** [comment]
Job PR-705-4 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-705/4/index.html

**Comment by szha** [comment]
Job PR-705-5 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-705/5/index.html

**Comment by szha** [comment]
Job PR-705-6 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-705/6/index.html

**Comment by szha** [comment]
Job PR-705-7 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-705/7/index.html

**Comment by szha** [comment]
Job PR-705-8 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-705/8/index.html

**Comment by szha** [comment]
Job PR-705-9 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-705/9/index.html

**Comment by szha** [comment]
Job PR-705-11 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-705/11/index.html

**Comment by szha** [comment]
Job PR-705-12 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-705/12/index.html

**Comment by szha** [comment]
Job PR-705-10 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-705/10/index.html

**Comment by szha** [comment]
Job PR-705-13 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-705/13/index.html

**Comment by szha** [comment]
Job PR-705-17 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-705/17/index.html

**Comment by szha** [comment]
Job PR-705-18 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-705/18/index.html

**Comment by szha** [comment]
Job PR-705-19 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-705/19/index.html

**Pull request merged**
