### PR TITLE
Update AutoMM presets

### PR DESCRIPTION
**Pull request by zhiqiangdon**
1. Add presets: `default`, `medium_quality_faster_train`, `high_quality`, and `best_quality` in AutoMM.
2. add the `preset` argument in `.fit()` and use it in `get_config()`.
3. Use registry for presets.
4. Add a function to return AutoMM's basic config.
5. Update some function names to be specific for AutoMM.

### CODE REVIEW

**Comment by sxjscience** [comment]
Need to add unittest about registry. You may copy the file in https://github.com/dmlc/gluon-nlp/blob/master/tests/test_utils_registry.py

**Comment by szha** [comment]
Job PR-1843-9 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1843/9/index.html

**Review by sxjscience — APPROVED** [review]
LGTM!

**Comment by szha** [comment]
Job PR-1843-10 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1843/10/index.html

**Comment by szha** [comment]
Job PR-1843-11 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1843/11/index.html

**Comment by szha** [comment]
Job PR-1843-12 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1843/12/index.html

**Review by bryanyzhu — APPROVED** [review]

**Pull request merged**
