### PR TITLE
Removed deprecated text_classification task

### PR DESCRIPTION
**Pull request by Innixma**
*Issue #, if available:*

*Description of changes:*

Removed deprecated text_classification task

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sxjscience** [comment]
In terms of the 0.1 release, I think we can remove the old `text classification`.

**Review by sxjscience — APPROVED** [review]
Looks good to me.

**Comment by Innixma** [comment]
> In terms of the 0.1 release, I think we can remove the old `text classification`.

Do you know of any other code that we can delete safely that isn't present in this PR?

**Comment by sxjscience** [comment]
> > In terms of the 0.1 release, I think we can remove the old `text classification`.
> 
> Do you know of any other code that we can delete safely that isn't present in this PR?

I think it has removed all codes related to TextClassification including the relative gluonnlp dependency in the CI.

**Comment by szha** [comment]
Job PR-729-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-729/1/index.html

**Pull request merged**
