### PR TITLE
Make ci simpler and easier to maintain

### PR DESCRIPTION
**Pull request by daikikatsuragawa**
With arrays and for statements, we can expect the following:
- Addition of processing when releasing a new function

### CODE REVIEW

**Comment by Innixma** [comment]
Thanks for the contribution! This looks good to me, I'll merge once CI passes.

**Review by Innixma — APPROVED** [review]

**Comment by szha** [comment]
Job PR-874-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-874/2/index.html

**Comment by daikikatsuragawa** [comment]
I am very grateful to AutoGluon, a very nice library. As a user, I want to contribute as much as possible!

**Comment by Innixma** [comment]
Great to hear! Here is an invite to our collaborator slack channel: https://join.slack.com/t/autogluon/shared_invite/zt-l5w9ljib-VcqlbgLklgjhzhTUV1BLwQ

**Pull request merged**
