### PR TITLE
Add notice to ensure serializable custom metrics

### PR DESCRIPTION
**Pull request by Innixma**
*Issue #, if available:*
#1637

*Description of changes:*
- Added instructions on how to make a custom metric serializable.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yinweisu** [comment]
Shall we add a pointer to this section in the FAQ?

**Comment by Innixma** [comment]
> Shall we add a pointer to this section in the FAQ?

good point, added

**Comment by szha** [comment]
Job PR-1705-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1705/1/index.html

**Comment by szha** [comment]
Job PR-1705-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1705/2/index.html

**Comment by szha** [comment]
Job PR-1705-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1705/3/index.html

**Review by yinweisu — APPROVED** [review]
LGTM

**Pull request merged**
