### PR TITLE
Update ConfigSpace dependency

### PR DESCRIPTION
**Pull request by jonashaag**
Fixes install when NumPy isn't already installed, see https://github.com/automl/ConfigSpace/pull/115

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-780-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-780/1/index.html

**Comment by Innixma** [comment]
Looks good to me! @jwmueller , @zhreshold was there any special reason we chose to limit the version in the past?

**Review by jwmueller — APPROVED** [review]

**Comment by jwmueller** [comment]
> was there any special reason we chose to limit the version in the past?

Not that I can recall. Perhaps one of the intermediate versions between 0.4.11 and 0.4.15 didn't work, but I think it should be ok to stick with 0.4.16 as the new limit regardless given this version appears to work.

**Review by zhreshold — APPROVED** [review]

**Review by Innixma — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
