### PR TITLE
Extra utils

### PR DESCRIPTION
**Pull request by mseeger**
*Issue #, if available:*

*Description of changes:*
Refactoring HPO and adding additional utilities (storing results, analyzing, plotting)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-929-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-929/3/index.html

**Comment by szha** [comment]
Job PR-929-4 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-929/4/index.html

**Comment by Innixma** [comment]
Do you think this is something that can be properly tested by the time we release v0.1 or would you recommend it be merged after?

**Comment by mseeger** [comment]
When is 0.1 released? This is not so super urgent.

**Comment by mseeger** [comment]
But just after the release, this should be considered. I am fixing/improving little things, and these PRs now and then are the mechanism to bring things back

**Comment by szha** [comment]
Job PR-929-5 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-929/5/index.html

**Comment by Innixma** [comment]
Planned release for Feb 26th, so we'd want this reviewed and tested very soon if it were to be part of v0.1.

**Comment by mseeger** [comment]
OK, I'll close it and re-open once v0.1 is released.

**Pull request closed without merging**
