### PR TITLE
Tabular: Optimized stopping metric

### PR DESCRIPTION
**Pull request by Innixma**
*Issue #, if available:*

*Description of changes:*

- AUC eval metric now directly uses AUC as stopping metric instead of log_loss

Next Steps:

- [ ] Benchmark

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-914-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-914/1/index.html

**Review by jwmueller — APPROVED** [review]

**Comment by szha** [comment]
Job PR-914-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-914/2/index.html

**Comment by szha** [comment]
Job PR-914-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-914/3/index.html

**Review by gradientsky — APPROVED** [review]

**Comment by Innixma** [comment]
For context on this PR, I did do a benchmark but it actually was slightly worse. I'm keeping this open for now in case I get a chance to retry the benchmark after all the latest changes, since it was somewhat surprising to me that it did not get an improvement.

**Review by gradientsky — APPROVED** [review]

**Pull request closed without merging**
