### PR TITLE
[fastai] addressed normalization bottleneck in fastai

### PR DESCRIPTION
**Pull request by gradientsky**
*Description of changes:*
fastai `Normalize` processor is not optimal: on the datasets with large number of continuous variables, it takes significant amount of time to perform normalization.
Small dataset benchmarking results:

task | result_old | metric_old | training_duration_old | acc_old | auc_old | balacc_old | logloss_old | result_new | metric_new | training_duration_new | acc_new | auc_new | balacc_new | logloss_new
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Australian | 0.936333 | auc | 32.4 | 0.869565 | 0.936333 | 0.875637 | 0.32122 | 0.949066 | auc | 43.9 | 0.884058 | 0.949066 | 0.882852 | 0.278797
blood-transfusion | 0.771442 | auc | 28.6 | 0.76 | 0.771442 | 0.595029 | 0.483829 | 0.758772 | auc | 24.1 | 0.746667 | 0.758772 | 0.605263 | 0.550954
car | -0.033726 | neg_logloss | 50.8 | 0.99422 | NaN | 0.99359 | 0.033726 | -0.022842 | neg_logloss | 41.3 | 0.99422 | NaN | 0.997934 | 0.022842
christine | 0.818848 | auc | 773.7 | 0.743542 | 0.818848 | 0.743542 | 0.522822 | 0.821694 | auc | 408.3 | 0.750923 | 0.821694 | 0.750923 | 0.519445
cnae-9 | -0.212781 | neg_logloss | 133.4 | 0.972222 | NaN | 0.972222 | 0.212781 | -0.163373 | neg_logloss | 130.2 | 0.953704 | NaN | 0.953704 | 0.163373
credit-g | 0.814286 | auc | 42.2 | 0.75 | 0.814286 | 0.659524 | 0.489898 | 0.819524 | auc | 37.1 | 0.77 | 0.819524 | 0.721429 | 0.475789
dilbert | -0.04709 | neg_logloss | 692.1 | 0.985 | NaN | 0.985161 | 0.04709 | -0.048778 | neg_logloss | 724.8 | 0.983 | NaN | 0.983099 | 0.048778
fabert | -0.815309 | neg_logloss | 407.6 | 0.695388 | NaN | 0.669743 | 0.815309 | -0.809688 | neg_logloss | 279.7 | 0.700243 | NaN | 0.669973 | 0.809688
jasmine | 0.846756 | auc | 74.5 | 0.792642 | 0.846756 | 0.792371 | 0.475694 | 0.842908 | auc | 70.2 | 0.799331 | 0.842908 | 0.798859 | 0.453398
kc1 | 0.830045 | auc | 48.5 | 0.872038 | 0.830045 | 0.629452 | 0.328639 | 0.839124 | auc | 46.5 | 0.872038 | 0.839124 | 0.655115 | 0.355251
kr-vs-kp | 0.999804 | auc | 56.5 | 0.990625 | 0.999804 | 0.99047 | 0.023755 | 0.999648 | auc | 53.5 | 0.9875 | 0.999648 | 0.987202 | 0.028402
mfeat-factors | -0.06438 | neg_logloss | 77.6 | 0.985 | NaN | 0.985 | 0.06438 | -0.062762 | neg_logloss | 71.6 | 0.98 | NaN | 0.98 | 0.062762
phoneme | 0.933765 | auc | 51.2 | 0.866913 | 0.933765 | 0.834165 | 0.29675 | 0.931114 | auc | 49.5 | 0.863216 | 0.931114 | 0.833383 | 0.301901
segment | -0.157093 | neg_logloss | 55 | 0.95671 | NaN | 0.95671 | 0.157093 | -0.162179 | neg_logloss | 50.8 | 0.95671 | NaN | 0.95671 | 0.162179
sylvine | 0.974039 | auc | 52.1 | 0.927875 | 0.974039 | 0.927795 | 0.194976 | 0.974055 | auc | 48.4 | 0.918129 | 0.974055 | 0.918052 | 0.204963
vehicle | -0.323918 | neg_logloss | 28.8 | 0.870588 | NaN | 0.871158 | 0.323918 | -0.307616 | neg_logloss | 27.5 | 0.905882 | NaN | 0.906926 | 0.307616

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-1389-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1389/1/index.html

**Comment by szha** [comment]
Job PR-1389-2 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1389/2/index.html

**Comment by szha** [comment]
Job PR-1389-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1389/3/index.html

**Comment by szha** [comment]
Job PR-1389-4 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1389/4/index.html

**Comment by Innixma** [comment]
Closed in favor of #1409

**Pull request closed without merging**
